# The targeted device
DEVICE=xc6slx45-3csg324

# The project name, can be pretty much anything
PROJECT=d_latch.prj
# The name of the top module vhdl file
TOP_MODULE=d_latch
# VHDL source files
VHDL=$(wildcard *.vhd)
# Name of the output image
OUTPUT=$(PROJECT:.prj=.bit)


include ../vhdl.mk
